apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service5
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/samgabrail/service5.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: service5
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # NOTE: Manual sync - students will trigger sync in ArgoCD
    # Uncomment below for auto-sync in production:
    # automated:
    #   prune: true
    #   selfHeal: true
